/**
 * Design constants for Sogni Music Bot
 */

module.exports = {
    COLORS: {
        PRIMARY: '#FF0055',    // Sogni Pink
        SECONDARY: '#5865F2',  // Discord Blurple
        SUCCESS: '#00FF99',    // Vibrant Green
        ERROR: '#FF3333',      // Vibrant Red
        INFO: '#00CCFF',       // Cyber Blue
        GLASS: '#1A1A1D'       // Dark background
    },
    EMOJIS: {
        MUSIC: '🎵',
        LOADING: '⌛',
        SUCCESS: '✅',
        ERROR: '❌',
        LYRICS: '✍️',
        INSTRUMENTAL: '🎧',
        THINKING: '🧠',
        GEAR: '⚙️',
        SPARKLES: '✨',
        WAVE: '🌊'
    },
    IMAGES: {
        BANNER: 'https://i.imgur.com/your-sogni-banner.png', // Placeholder for now
        ICON: 'https://i.imgur.com/your-sogni-icon.png'
    },
    STYLES: {
        "afro-cuban": "Afro-Cuban, conga drums, timbales, montuno piano, brass section, son clave rhythm, tropical energy",
        "afrobeats": "afrobeats, infectious percussion, highlife guitar licks, dancehall influence, vibrant rhythm, tropical energy",
        "alternative rock": "alternative rock, distorted guitars, dynamic shifts, raw vocals, atmospheric textures, 90s influenced",
        "amapiano": "amapiano, log drum bass, shaker percussion, jazzy piano chords, South African deep house, infectious bounce",
        "ambient": "ambient, slow-evolving textures, atmospheric drones, spacious reverb, meditative pads, tranquil soundscape",
        "ambient electronic": "ambient electronic, lush synth textures, evolving soundscapes, ethereal pads, slow builds, immersive atmosphere",
        "americana": "Americana, roots rock, pedal steel guitar, storytelling lyrics, warm acoustic tones, heartland spirit",
        "art pop": "art pop, experimental arrangements, avant-garde production, eclectic instrumentation, bold artistic expression",
        "bachata": "bachata, romantic guitar arpeggios, bongo drums, güira, smooth bass, Latin passion, danceable groove",
        "baroque": "baroque, harpsichord, ornate counterpoint, chamber strings, structured elegance, period instrumentation",
        "bebop": "bebop jazz, fast tempo, complex chord changes, virtuoso improvisation, walking bass, swinging drums",
        "bedroom pop": "bedroom pop, intimate lo-fi vocals, dreamy reverb, soft synth pads, gentle guitar, hazy atmosphere",
        "black metal": "black metal, blast beats, tremolo-picked guitars, shrieking vocals, raw lo-fi production, icy dark atmosphere",
        "bluegrass": "bluegrass, fast banjo picking, fiddle, mandolin, upright bass, vocal harmonies, Appalachian energy",
        "blues": "blues, expressive guitar bends, 12-bar structure, soulful feeling, Hammond organ, walking bass, raw emotion",
        "blues rock": "blues rock, overdriven guitar, pentatonic riffs, driving rhythm, powerful drums, gritty soulful energy",
        "boom bap": "boom bap, classic hip hop drums, chopped soul samples, heavy kick and snare, vinyl warmth, head-nodding groove",
        "bossa nova": "bossa nova, nylon guitar, gentle samba rhythm, warm bass, soft brushes, intimate Brazilian elegance",
        "celtic": "Celtic, fiddle, tin whistle, bodhrán drum, acoustic guitar, Irish folk melodies, lively dance rhythm",
        "chamber music": "chamber music, intimate string quartet, delicate interplay, refined dynamics, classical elegance",
        "chillstep": "chillstep, melodic dubstep, soft wobble bass, atmospheric pads, ethereal vocals, dreamy drops",
        "chiptune": "chiptune, 8-bit square waves, retro game console sounds, energetic arpeggios, nostalgic pixel-era melodies",
        "classic rock": "classic rock, electric guitar riffs, powerful drums, blues-inspired solos, driving bass, anthemic energy",
        "classical": "classical, full orchestra, sweeping strings, elegant piano, refined composition, dynamic expression",
        "cloud rap": "cloud rap, ethereal synth pads, dreamy atmosphere, slow tempo, reverb-heavy, spacey lo-fi beats",
        "country": "country, acoustic guitar, steel guitar, fiddle, steady rhythm, warm twangy vocals, Nashville production",
        "country pop": "country pop, twangy electric guitar, modern polished production, anthemic chorus, Nashville meets pop hooks",
        "dance pop": "dance pop, upbeat tempo, catchy synth hooks, four-on-the-floor rhythm, polished production, radio-ready",
        "death metal": "death metal, brutal blast beats, deep guttural vocals, down-tuned guitars, relentless double bass drumming",
        "deep house": "deep house, warm basslines, soulful chords, four-on-the-floor kick, smooth groove, late-night club vibe",
        "disco": "disco, four-on-the-floor kick, funky bass, lush strings, rhythmic guitar, shimmering hi-hats, dance floor groove",
        "documentary": "documentary score, understated piano, ambient textures, subtle strings, reflective mood, emotional clarity",
        "dream pop": "dream pop, shimmering reverb guitars, ethereal vocals, hazy atmosphere, lush layered synths, blissful soundscape",
        "drone": "drone, sustained tones, slowly shifting harmonics, deep resonance, hypnotic overtones, immersive texture",
        "drum & bass": "drum and bass, fast breakbeats, heavy sub bass, rolling rhythms, energetic percussion, high-tempo drive",
        "dub": "dub, heavy bass drops, echo-drenched percussion, spacious reverb, stripped-down reggae, psychedelic effects",
        "dubstep": "dubstep, aggressive wobble bass, half-time drums, heavy drops, distorted synths, powerful sub frequencies",
        "edm": "EDM, massive festival drops, soaring synth leads, four-on-the-floor beats, euphoric build-ups, high energy",
        "electropop": "electropop, pulsing synthesizers, crisp electronic beats, catchy vocal hooks, bright polished production",
        "epic cinematic": "epic cinematic, massive orchestral swells, thundering percussion, heroic brass fanfares, dramatic tension, blockbuster scale",
        "film score": "film soundtrack, orchestral underscore, emotional strings, thematic motifs, atmospheric tension, cinematic depth",
        "flamenco": "flamenco, passionate nylon guitar, percussive hand claps, cajón, intense strumming, Spanish fire",
        "folk": "folk, acoustic guitar, harmonica, warm vocals, storytelling, organic instrumentation, earthy atmosphere",
        "funk": "funk, slap bass, tight rhythmic guitar, punchy horns, syncopated drums, groovy clavinet, infectious groove",
        "glitch": "glitch, stuttering digital artifacts, fragmented beats, granular synthesis, experimental textures, IDM influence",
        "gospel": "gospel, powerful choir harmonies, Hammond organ, uplifting piano, soulful expression, spiritual energy",
        "grunge": "grunge, heavy distorted guitars, raw aggressive vocals, sludgy bass, pounding drums, angst-driven energy",
        "heavy metal": "heavy metal, powerful guitar riffs, soaring lead guitar, double bass drums, epic anthemic energy, headbanging tempo",
        "hip hop": "hip hop, heavy beats, sampled loops, strong bass, rhythmic flow, urban groove, head-nodding tempo",
        "house": "house music, steady four-on-the-floor kick, groovy bassline, funky loops, uplifting chords, dance floor energy",
        "indie pop": "indie pop, jangly guitars, upbeat tempo, catchy melodies, bright synths, youthful energy",
        "indie rock": "indie rock, jangling guitars, lo-fi warmth, understated vocals, driving rhythm section, DIY aesthetic",
        "industrial": "industrial, harsh mechanical rhythms, distorted synths, metallic percussion, aggressive textures, dark power",
        "jazz": "jazz, smooth saxophone, walking bass, brushed drums, warm piano chords, late-night club atmosphere",
        "k-pop": "K-pop, polished production, dynamic arrangement, catchy hooks, electronic beats, energetic dance pop",
        "latin pop": "Latin pop, bright rhythms, Spanish guitar accents, polished production, infectious groove, crossover appeal",
        "latin trap": "Latin trap, heavy 808 bass, dembow-influenced hi-hats, Spanish vocals, dark melodies, urban Latin grit",
        "lo-fi chill": "lo-fi hip hop, mellow beats, warm vinyl crackle, jazzy chords, relaxed grooves, cozy atmosphere",
        "meditation": "meditation music, gentle singing bowls, soft nature sounds, calming pads, slow tempo, peaceful serenity",
        "metalcore": "metalcore, heavy breakdowns, aggressive riffs, melodic passages, intense drumming, dynamic contrasts",
        "neo soul": "neo soul, warm Rhodes piano, smooth bass grooves, jazzy harmonies, soulful vocals, organic live feel",
        "new age": "new age, gentle piano, soft synth washes, nature-inspired melodies, healing atmosphere, serene flow",
        "orchestral": "orchestral, full symphony orchestra, rich strings, powerful brass, soaring woodwinds, grand scale",
        "phonk": "phonk, distorted 808 bass, chopped Memphis samples, cowbell hits, dark atmosphere, aggressive drift energy",
        "pop": "pop, catchy melodies, polished production, upbeat rhythm, bright instrumentation, mainstream appeal",
        "post-rock": "post-rock, crescendo guitar layers, expansive soundscapes, atmospheric delay, emotional build-ups, cinematic resolution",
        "progressive rock": "progressive rock, complex time signatures, extended compositions, layered keyboards, virtuoso guitar, epic arrangements",
        "punk rock": "punk rock, fast aggressive chords, raw energy, shouted vocals, driving tempo, stripped-down production",
        "r&b": "R&B, smooth vocals, lush harmonies, slow groove, warm bass, sultry atmosphere, polished production",
        "reggae": "reggae, offbeat guitar skank, deep bass, one-drop drums, laid-back groove, warm island vibes",
        "reggaeton": "reggaeton, dembow rhythm, heavy bass, dancehall influence, urban Latin beats, club energy",
        "romantic era": "romantic era classical, expressive melodies, lush orchestration, emotional depth, virtuoso piano, sweeping dynamics",
        "salsa": "salsa, bright brass section, conga drums, piano montuno, timbales, energetic dance rhythm, Caribbean heat",
        "shoegaze": "shoegaze, walls of distorted guitar, heavy reverb, dreamy buried vocals, swirling effects, ethereal noise",
        "ska": "ska, upbeat offbeat guitar, walking bass, brass section, fast tempo, energetic dance rhythm, Jamaican roots",
        "smooth jazz": "smooth jazz, mellow saxophone, soft electric piano, gentle groove, polished production, relaxing mood",
        "soul": "soul music, warm expressive vocals, Motown-inspired rhythm, brass accents, vintage warmth, emotional depth",
        "synthwave": "synthwave, retro 80s synths, pulsing bassline, electronic drums, neon-lit nostalgic atmosphere",
        "techno": "techno, driving kick drum, hypnotic repetition, dark industrial textures, modular synths, relentless groove",
        "trance": "trance, uplifting arpeggios, euphoric pads, driving beats, layered synths, soaring emotional melodies",
        "trap": "trap, booming 808s, rapid hi-hat rolls, dark melodies, heavy bass drops, atmospheric ad-libs",
        "trip-hop": "A trip-hop song, dark, cinematic, and melancholic sound. The style blends haunting, dark female vocals with lo-fi, hip-hop-influenced beats and atmospheric, often distorted guitars",
        "vaporwave": "vaporwave, slowed-down samples, nostalgic 80s synths, reverb-drenched, lo-fi aesthetics, surreal atmosphere",
        "video game": "video game soundtrack, chiptune influences, dynamic electronic layers, adaptive arrangement, adventurous energy"
    }
};
